// Holla Americana — All 21 tour packages data

export interface Package {
  id: number;
  title: string;
  days: number;
  nights: number;
  price: number | null;
  countries: string[];
  categories: string[];
  image: string;
  slug: string;
}

export const CATEGORIES = [
  { id: "adventure", label: "Adventure", icon: "🏔️" },
  { id: "amazon", label: "Amazon", icon: "🌿" },
  { id: "beaches", label: "Beaches", icon: "🏖️" },
  { id: "cities", label: "Cities", icon: "🏙️" },
  { id: "culture", label: "Culture", icon: "🎭" },
  { id: "desert", label: "Desert", icon: "🏜️" },
  { id: "eco-lodge", label: "Eco Lodge", icon: "🌱" },
  { id: "glaciers", label: "Glaciers", icon: "🧊" },
  { id: "grand-tours", label: "Grand Tours", icon: "🗺️" },
  { id: "group-tours", label: "Group Tours", icon: "👥" },
  { id: "heritage", label: "Heritage", icon: "🏛️" },
  { id: "history", label: "History", icon: "📜" },
  { id: "lakes", label: "Lakes", icon: "💧" },
  { id: "luxury", label: "Luxury", icon: "💎" },
  { id: "mountains", label: "Mountains", icon: "⛰️" },
  { id: "multi-country", label: "Multi-Country", icon: "🌎" },
  { id: "nature", label: "Nature", icon: "🌳" },
  { id: "patagonia", label: "Patagonia", icon: "🦅" },
  { id: "salt-flats", label: "Salt Flats", icon: "🪨" },
  { id: "wildlife", label: "Wildlife", icon: "🦜" },
  { id: "wonders", label: "Wonders", icon: "✨" },
];

export const COUNTRIES = [
  "Argentina",
  "Bolivia",
  "Brazil",
  "Chile",
  "Peru",
];

export const PRICE_RANGES = [
  { label: "All Prices", min: 0, max: Infinity },
  { label: "Under $2,000", min: 0, max: 2000 },
  { label: "$2,000 – $4,000", min: 2000, max: 4000 },
  { label: "$4,000 – $6,000", min: 4000, max: 6000 },
  { label: "$6,000 – $10,000", min: 6000, max: 10000 },
  { label: "Over $10,000", min: 10000, max: Infinity },
];

// Unsplash images for each package (relevant to destination)
export const PACKAGES: Package[] = [
  {
    id: 1,
    title: "Ultimate Patagonia Tour: Chile & Argentina 2026",
    days: 8,
    nights: 7,
    price: 3507,
    countries: ["Argentina", "Chile"],
    categories: ["patagonia", "glaciers", "adventure", "nature", "mountains"],
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80",
    slug: "ultimate-patagonia-tour",
  },
  {
    id: 2,
    title: "Manaus Amazon Eco Lodge Experience 2026",
    days: 4,
    nights: 3,
    price: 1705,
    countries: ["Brazil"],
    categories: ["amazon", "eco-lodge", "wildlife", "nature"],
    image: "https://images.unsplash.com/photo-1518182170546-07661fd94144?w=600&q=80",
    slug: "manaus-amazon-eco-lodge",
  },
  {
    id: 3,
    title: "Incredible Argentina Tour 2026",
    days: 13,
    nights: 12,
    price: 4496,
    countries: ["Argentina", "Brazil"],
    categories: ["cities", "adventure", "culture", "grand-tours"],
    image: "https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=600&q=80",
    slug: "incredible-argentina-tour",
  },
  {
    id: 4,
    title: "Inca Express Group Tour: Lima, Cusco & Machu Picchu 2026",
    days: 7,
    nights: 6,
    price: 2320,
    countries: ["Peru"],
    categories: ["heritage", "history", "culture", "group-tours", "wonders"],
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=600&q=80",
    slug: "inca-express-group-tour",
  },
  {
    id: 5,
    title: "Explore Brazil Like Blu 2026",
    days: 12,
    nights: 11,
    price: 3884,
    countries: ["Brazil"],
    categories: ["cities", "beaches", "culture", "nature"],
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=600&q=80",
    slug: "explore-brazil-like-blu",
  },
  {
    id: 6,
    title: "Brazil Highlights Tour: São Paulo, Manaus, Rio & Iguazú 2026",
    days: 12,
    nights: 11,
    price: 4294,
    countries: ["Brazil"],
    categories: ["cities", "amazon", "nature", "wonders", "grand-tours"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    slug: "brazil-highlights-tour",
  },
  {
    id: 7,
    title: "Bariloche & Buenos Aires Tour 2026",
    days: 6,
    nights: 5,
    price: 1597,
    countries: ["Argentina"],
    categories: ["cities", "lakes", "mountains", "nature"],
    image: "https://images.unsplash.com/photo-1612294037637-ec328d0e075e?w=600&q=80",
    slug: "bariloche-buenos-aires-tour",
  },
  {
    id: 8,
    title: "Ice to Sun: Brazil & Argentina Tour 2026",
    days: 10,
    nights: 9,
    price: 2675,
    countries: ["Argentina", "Brazil"],
    categories: ["glaciers", "beaches", "cities", "adventure"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    slug: "ice-to-sun-brazil-argentina",
  },
  {
    id: 9,
    title: "VIP Chile Luxury Tour 2026",
    days: 10,
    nights: 9,
    price: 9248,
    countries: ["Chile"],
    categories: ["luxury", "desert", "cities", "nature", "salt-flats"],
    image: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=80",
    slug: "vip-chile-luxury-tour",
  },
  {
    id: 10,
    title: "Rio, Manaus & Iguazú Explorer Tour 2026",
    days: 8,
    nights: 7,
    price: 3660,
    countries: ["Brazil"],
    categories: ["cities", "amazon", "wonders", "nature"],
    image: "https://images.unsplash.com/photo-1619546952812-520e98064a52?w=600&q=80",
    slug: "rio-manaus-iguazu-explorer",
  },
  {
    id: 11,
    title: "3 Countries South America Tour: Brazil, Argentina & Chile 2026",
    days: 15,
    nights: 14,
    price: 4850,
    countries: ["Brazil", "Argentina", "Chile"],
    categories: ["multi-country", "grand-tours", "cities", "nature"],
    image: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=600&q=80",
    slug: "3-countries-brazil-argentina-chile",
  },
  {
    id: 12,
    title: "4 Nations + 1 Unforgettable Journey South America 2026",
    days: 16,
    nights: 15,
    price: 6215,
    countries: ["Brazil", "Argentina", "Chile", "Peru"],
    categories: ["multi-country", "grand-tours", "heritage", "wonders"],
    image: "https://images.unsplash.com/photo-1553697388-94e804e2f0f6?w=600&q=80",
    slug: "4-nations-journey-south-america",
  },
  {
    id: 13,
    title: "5 Countries Grand South America Tour 2026",
    days: 18,
    nights: 17,
    price: 7561,
    countries: ["Brazil", "Argentina", "Chile", "Bolivia", "Peru"],
    categories: ["multi-country", "grand-tours", "salt-flats", "wonders"],
    image: "https://images.unsplash.com/photo-1580619305218-8423a7ef79b4?w=600&q=80",
    slug: "5-countries-grand-south-america",
  },
  {
    id: 14,
    title: "5 Countries Latin America Grand Tour 2026",
    days: 18,
    nights: 17,
    price: 7561,
    countries: ["Brazil", "Argentina", "Chile", "Bolivia", "Peru"],
    categories: ["multi-country", "grand-tours", "culture", "history"],
    image: "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=600&q=80",
    slug: "5-countries-latin-america-grand-tour",
  },
  {
    id: 15,
    title: "Group Tour Peru: Lima, Cusco & Puerto Maldonado 2026",
    days: 10,
    nights: 9,
    price: 3250,
    countries: ["Peru"],
    categories: ["group-tours", "heritage", "amazon", "wildlife", "history"],
    image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=600&q=80",
    slug: "group-tour-peru",
  },
  {
    id: 16,
    title: "3 Countries South America Tour: Chile, Argentina & Brazil 2026",
    days: 15,
    nights: 14,
    price: 5150,
    countries: ["Chile", "Argentina", "Brazil"],
    categories: ["multi-country", "grand-tours", "cities", "desert"],
    image: "https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80",
    slug: "3-countries-chile-argentina-brazil",
  },
  {
    id: 17,
    title: "Chile & Argentina Deluxe Tour 2026",
    days: 14,
    nights: 13,
    price: null,
    countries: ["Chile", "Argentina", "Brazil"],
    categories: ["luxury", "cities", "patagonia", "nature"],
    image: "https://images.unsplash.com/photo-1524850011238-e3d235c7d4c9?w=600&q=80",
    slug: "chile-argentina-deluxe-tour",
  },
  {
    id: 18,
    title: "Brazil Grand Explorer Tour 2026",
    days: 11,
    nights: 10,
    price: 4294,
    countries: ["Brazil", "Argentina"],
    categories: ["grand-tours", "cities", "nature", "wonders"],
    image: "https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=600&q=80",
    slug: "brazil-grand-explorer-tour",
  },
  {
    id: 19,
    title: "Grand South America Trio: Brazil, Argentina & Chile 2026",
    days: 15,
    nights: 14,
    price: 4850,
    countries: ["Brazil", "Argentina", "Chile"],
    categories: ["multi-country", "grand-tours", "cities", "adventure"],
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&q=80",
    slug: "grand-south-america-trio",
  },
  {
    id: 20,
    title: "4 Nations + 1 Unforgettable Journey 2026",
    days: 15,
    nights: 14,
    price: 6215,
    countries: ["Brazil", "Argentina", "Chile", "Peru"],
    categories: ["multi-country", "grand-tours", "heritage", "culture"],
    image: "https://images.unsplash.com/photo-1531761535209-180857e963b9?w=600&q=80",
    slug: "4-nations-journey-2026",
  },
  {
    id: 21,
    title: "Ultimate South America – 5 Countries Grand Tour 2026",
    days: 22,
    nights: 21,
    price: 9995,
    countries: ["Brazil", "Argentina", "Chile", "Bolivia", "Peru"],
    categories: ["multi-country", "grand-tours", "luxury", "wonders", "adventure"],
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    slug: "ultimate-south-america-5-countries",
  },
];
